# -*- coding: utf-8 -*-
"""gen-demo-data.py — generate bulk FICTIONAL demo data for the v2 scaling demo.

Deterministic (seeded) so the demo is reproducible. Writes three files in the
same append-only push-log format as the real inquiry-log.js:

  inquiry-log.js                 (ACTIVE  — recent, what the board loads by default)
  inquiry-log-archive-2026H1.js  (ARCHIVE — older half-year)
  inquiry-log-archive-2025H2.js  (ARCHIVE — older half-year)

All names/teams/text are invented for demonstration. No real data.
Run: python gen-demo-data.py
"""
import json, random, os

random.seed(42)
HERE = os.path.dirname(os.path.abspath(__file__))

TYPES   = ["simple", "request", "urgent"]
TYPE_W  = [0.5, 0.4, 0.1]
PEOPLE  = ["alice", "bob", "carol", "dave", "erin", "frank", "grace", "heidi", "ivan", "judy"]
TEAMS   = ["sales", "finance", "accounting", "logistics", "purchasing", "IT", "HR"]
Q = [
    "How do I look up a user's employee number?",
    "Sales order delivery date needs to change; tax invoice already issued.",
    "ABAP dump when issuing a corrective (minus) tax invoice.",
    "Reset password for a shared account.",
    "Which T-Code shows the monthly billing run?",
    "Credit limit check is blocking an order.",
    "Material not appearing in the delivery-request list.",
    "Tax invoice amount is wrong and needs a correction.",
    "Approval route went to the highest tier unexpectedly.",
    "Stamp tax auto-calc came out lower than expected.",
    "How do I cancel a posted billing document?",
    "Return order doesn't show up in the report.",
    "Pricing condition not applied to a line item.",
    "Overnight batch job for the sales plan failed.",
    "A user can't see another rep's orders.",
]
A = [
    "Guided to the right T-Code; resolved.",
    "Root cause was a config boundary condition; corrected and re-tested.",
    "Handed off to the owning team; tracked to closure.",
    "Data fix applied through the formal change process.",
    "Explained the standard procedure; no system change needed.",
    "Reproduced, traced to code, fixed and verified.",
    "Authorization gap, not a bug; routed to the right team.",
    "Calculation method adjusted; turned into an improvement item.",
]

def chip():
    return random.choice(PEOPLE) + " / " + random.choice(TEAMS)

def gen(n, year, months, seq_start):
    """Return (push_rows, next_seq). Each inquiry = 1..3 pushes (append-only transitions)."""
    dates = sorted((year, random.choice(months), random.randint(1, 28)) for _ in range(n))
    rows, seq = [], seq_start
    for (y, mm, dd) in dates:
        seq += 1
        iid  = "INQ-%02d%02d%02d-%04d" % (y % 100, mm, dd, seq)
        date = "%04d-%02d-%02d" % (y, mm, dd)
        t    = random.choices(TYPES, TYPE_W)[0]
        rows.append({"id": iid, "date": date, "type": t, "q": random.choice(Q),
                     "by": random.choice(PEOPLE), "req": chip(), "status": "received"})
        roll = random.random()
        if roll < 0.82:                         # done (with transitions)
            rows.append({"id": iid, "status": "in-progress"})
            rows.append({"id": iid, "status": "done", "a": random.choice(A), "ref": ""})
        elif roll < 0.92:                        # still in progress
            rows.append({"id": iid, "status": "in-progress", "a": random.choice(A)})
        else:                                    # waiting on another team
            rows.append({"id": iid, "status": "waiting", "a": "Waiting on another team."})
    return rows, seq

HEADER = (
    "// ── Inquiry / request history (append-only push log, merged by id) ──\n"
    "// ⚠️ FICTIONAL bulk demo data generated by gen-demo-data.py (seeded, reproducible).\n"
    "//    Same format as the real inquiry-log.js. This file = {tag}.\n"
    "window.INQUIRY_LOG = window.INQUIRY_LOG || [];\n"
)

def write(path, rows, tag):
    with open(os.path.join(HERE, path), "w", encoding="utf-8") as f:
        f.write(HEADER.format(tag=tag))
        for r in rows:
            f.write("window.INQUIRY_LOG.push(" + json.dumps(r, ensure_ascii=False) + ");\n")

# Generate oldest -> newest so ids/seq read chronologically.
h2, seq = gen(120, 2025, [8, 9, 10, 11, 12], 0)        # 2025 H2
h1, seq = gen(150, 2026, [1, 2, 3, 4], seq)            # 2026 H1 (older part)
active, seq = gen(45, 2026, [5, 6], seq)               # ACTIVE (recent)

write("inquiry-log-archive-2025H2.js", h2, "ARCHIVE 2025 H2")
write("inquiry-log-archive-2026H1.js", h1, "ARCHIVE 2026 H1")
write("inquiry-log.js", active, "ACTIVE (recent)")

def uniq(rows):
    return len({r["id"] for r in rows})

print("ACTIVE     inquiry-log.js                : %3d inquiries, %3d pushes" % (uniq(active), len(active)))
print("ARCHIVE    inquiry-log-archive-2026H1.js : %3d inquiries, %3d pushes" % (uniq(h1), len(h1)))
print("ARCHIVE    inquiry-log-archive-2025H2.js : %3d inquiries, %3d pushes" % (uniq(h2), len(h2)))
print("TOTAL      : %d inquiries, %d pushes" % (uniq(active+h1+h2), len(active)+len(h1)+len(h2)))
